/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/26419182-c141-47cf-ac97-c9c860674a12 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float ppm_co2;
  float volts;
  CloudTemperatureSensor temperature;
  int relay_pin_1_out;
  CloudPercentage dac1_in;
  CloudPercentage dac2_in;
  CloudPercentage dac3_in;
  CloudPercentage dac4_in;
  CloudPercentage dac5_in;
  CloudPercentage dac6_in;
  CloudPercentage dac7_in;
  CloudPercentage dac8_in;
  CloudPercentage dim1_out;
  CloudPercentage dim2_out;
  CloudPercentage dim3_out;
  CloudPercentage dim4_out;
  CloudPercentage dim5_out;
  CloudPercentage dim6_out;
  CloudPercentage dim7_out;
  CloudPercentage dim8_out;
  CloudRelativeHumidity humidity;
  bool dac_Auto;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

//#include "thingProperties.h"

#include <WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
#include "DHT.h"
#include <Wire.h>
#include <Adafruit_MCP4725.h>
#include "RTClib.h"
#include "FS.h"
#include "SD.h"
#include "SPI.h"
//#include "pwmWrite.h"

float ppm_co2;
float volts;
float temperature;
int relay_pin_1_out;
int dac1_in;
int dac2_in;
int dac3_in;
int dac4_in;
int dac5_in;
int dac6_in;
int dac7_in;
int dac8_in;
int dim1_out;
int dim2_out;
int dim3_out;
int dim4_out;
int dim5_out;
int dim6_out;
int dim7_out;
int dim8_out;
float humidity;
bool dac_Auto;

// Configurações WiFi
//const char* ssid = "Injerauto";
//const char* password = "injerauto040316";
const char* ssid = "Martinho";
const char* password = "m@rl1m@rt1nh0";


// Configurações MQTT
const char* mqtt_server = "192.168.100.93";
const char* mqtt_user = "guest";
const char* mqtt_pass = "guest";

const char* mqtt_dim = "bru/luz";
const char* mqtt_command_dim = "bru/luz/cmd"; // Tópico para receber comandos
const char* mqtt_temp1 = "bru/temp1";
const char* mqtt_command_temp1 = "bru/temp1/cmd"; // Tópico para receber comandos
const char* mqtt_humidity = "bru/humidity";
const char* mqtt_command_humidity = "bru/humidity/cmd"; // Tópico para receber comandos

unsigned long lastReconnectAttempt = 0;
unsigned long intervaloEnvio = 5000; // Intervalo padrão de 5 segundos para envio de mensagens
unsigned long ultimoEnvio = 0; // Controla a última vez que uma mensagem foi enviada

bool enviarInformacoes = true; // Controla se as informações devem ser enviadas

WiFiClient espClient;
PubSubClient client(espClient);

#define DHT_PIN 25
#define DHT_TYPE DHT22
#define DHT_TEMPERATURE_OFFSET -3.35
#define DHT_HUMIDITY_OFFSET +0.0
#define DHT_TEMPERATURE_GAIN +1.0
#define DHT_HUMIDITY_GAIN +1.0

//#define MG811PIN 32 

#define HSPI_MISO   13
#define HSPI_MOSI   14
#define HSPI_SCLK   27
#define HSPI_SS     26

#define _SDA1 22
#define _SCL1 23
#define _SDA2 32
#define _SCL2 33

#define RELAY_PIN_1 15

#define PWM_PIN_1 4
#define PWM_PIN_2 16
#define PWM_PIN_3 17
#define PWM_PIN_4 18

#define WTD_PIN 19
#define CLOUD_DISCONNECTED_COUNTER_MAX 120 // 10 minutos para loopPeriod = 5000

//DAC 0,25 - 4,75V
#define DIMMING_MAX_DAC 95
#define DIMMING_MIN_DAC 5
//PWM
#define DIMMING_MAX_PWM 90
#define DIMMING_MIN_PWM 10

DHT dht( DHT_PIN , DHT_TYPE );

TwoWire _Wire1 = TwoWire( 0 );
TwoWire _Wire2 = TwoWire( 1 );

Adafruit_MCP4725 dac1_out , dac2_out , dac3_out , dac4_out;

RTC_DS3231 rtc;
DateTime now;

//Pwm pwm = Pwm();

long millisPrev;
//long loopPeriod = 1 * 1000;
long loopPeriod = 500;

uint8_t cloudDisconnectedCounter = 0;

int32_t DefaultPWMduty = 0;
float DefaultPWMfrequency = 1000;
uint8_t DefaultPWMresolution = 12;
uint32_t DefaultPWMphase = 0;

uint16_t prevHour = 0;
bool clockInSync = 0;
char daysOfTheWeek[7][12] = {"Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"};

#define DIMMING_POINTS_MAX 50
typedef struct dimming_t{
  
  uint8_t dimmingPoints;
  uint8_t hours[ DIMMING_POINTS_MAX ];
  uint8_t minutes[ DIMMING_POINTS_MAX ];
  uint8_t seconds[ DIMMING_POINTS_MAX ];
  long secondsSinceStart[ DIMMING_POINTS_MAX ];
  uint8_t value[ DIMMING_POINTS_MAX ];
  
}dimming_t;

dimming_t dimCH1;
dimming_t dimCH2;
dimming_t dimCH3;
dimming_t dimCH4;
//dimming_t dimCH5;
//dimming_t dimCH6;
//dimming_t dimCH7;
//dimming_t dimCH8;

void setup(){

  relay_pin_1_out = LOW;
  pinMode( RELAY_PIN_1 , OUTPUT ); digitalWrite( RELAY_PIN_1 , relay_pin_1_out );
  pinMode( LED_BUILTIN , OUTPUT );
  pinMode( WTD_PIN , OUTPUT );
  
  // Initialize serial and wait for port to open:
  Serial.begin( 115200 );
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay( 1500 ); 
  
  _Wire1.begin( _SDA1 , _SCL1 , 400000ul );
  _Wire2.begin( _SDA2 , _SCL2 , 400000ul );
  
  Serial.println("Start...");
  digitalWrite( LED_BUILTIN , HIGH ); delay(300);
  digitalWrite( LED_BUILTIN , LOW );  delay(300);
  digitalWrite( LED_BUILTIN , HIGH ); delay(300);
  digitalWrite( LED_BUILTIN , LOW );  delay(300);
  digitalWrite( LED_BUILTIN , HIGH ); delay(50);
  digitalWrite( LED_BUILTIN , LOW );
  
  dht.begin();

  dac1_out.begin( 0x61 , &_Wire1 );
  dac2_out.begin( 0x60 , &_Wire1 );
  dac3_out.begin( 0x61 , &_Wire2 );
  dac4_out.begin( 0x60 , &_Wire2 );
  
  if ( !rtc.begin( &_Wire1 ) ){
    Serial.println("Couldn't find RTC");
    Serial.flush();
    Serial.println(F("Reiniciando ESP32..."));
    ESP.restart();
  }
  
  SPIClass *spi = NULL;
  spi = new SPIClass( HSPI );
  spi->begin( HSPI_SCLK , HSPI_MISO , HSPI_MOSI , HSPI_SS );
  
  if( !SD.begin( HSPI_SS , *spi ) ){
    Serial.println("Card Mount Failed");
    Serial.println(F("Reiniciando ESP32..."));
    ESP.restart();
  }
  
  uint8_t cardType = SD.cardType();
  if( cardType == CARD_NONE ){
    Serial.println("No SD card attached");
    Serial.println(F("Reiniciando ESP32..."));
    ESP.restart();
  }

  Serial.print("SD Card Type: ");
  if(cardType == CARD_MMC) Serial.println("MMC");
  else if(cardType == CARD_SD) Serial.println("SDSC");
  else if(cardType == CARD_SDHC) Serial.println("SDHC");
  else Serial.println("UNKNOWN");
  
  uint64_t cardSize = SD.cardSize() / (1024 * 1024);
  Serial.printf("SD Card Size: %lluMB\n", cardSize);
  Serial.printf("Total space: %lluMB\n", SD.totalBytes() / (1024 * 1024));
  Serial.printf("Used space: %lluMB\n", SD.usedBytes() / (1024 * 1024));
  
  getDimmingTable();
  
  bootLog();

  // Defined in thingProperties.h
 // initProperties();

  // Connect to Arduino IoT Cloud
  //ArduinoCloud.begin( ArduinoIoTPreferredConnection );
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  //setDebugMessageLevel( 4 );
  //ArduinoCloud.printDebugInfo();

  
  // Conectando-se à rede WiFi
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi conectado");
  Serial.println("Endereço IP: ");
  Serial.println(WiFi.localIP());

  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);

  reconnect(); // Conecta ao servidor MQTT pela primeira vez
  
  millisPrev = millis();
  
}

void callback(char* topic, byte* message, unsigned int length) {
  Serial.print("Mensagem recebida [");
  Serial.print(topic);
  Serial.print("] ");

  char msg[length + 1];
  memcpy(msg, message, length);
  msg[length] = '\0'; // Adiciona o terminador de string
  Serial.println(msg); // Exibe a mensagem

  StaticJsonDocument<200> doc;
  DeserializationError error = deserializeJson(doc, msg);

  if (error) {
    Serial.print("deserializeJson() falhou: ");
    Serial.println(error.c_str());
    return;
  }

  const char* comando = doc["comando"];

  // Processa o comando recebido
  if (strcmp(comando, "dac1") == 0) {
    const char* value = doc["value"];
    Serial.print("value: ");Serial.println(value);
    dac1_in = atoi(value);
    //intervaloEnvio = 2000; // Ajusta para 2 segundos
    //Serial.println("Intervalo ajustado para 2 segundos");
  } else if (strcmp(comando, "intervalo_5_segundos") == 0) {

    intervaloEnvio = 5000; // Ajusta para 5 segundos
    //Serial.println("Intervalo ajustado para 5 segundos");
  } else if (strcmp(comando, "stop") == 0) {
    enviarInformacoes = false; // Para o envio de informações
    Serial.println("Envio de informações parado");
  } else if (strcmp(comando, "send") == 0) {
    enviarInformacoes = true; // Retoma o envio de informações
    Serial.println("Envio de informações retomado");
  }
}

bool tryReconnect() {
  // Loop até estar conectado
  if (client.connect("ESP32Client", mqtt_user, mqtt_pass)) {
    // Reinscrever
    client.subscribe(mqtt_command_dim); // Assina o tópico de comandos
    client.subscribe(mqtt_command_temp1); // Assina o tópico de comandos
    client.subscribe(mqtt_command_humidity); // Assina o tópico de comandos
  }
  return client.connected();
}

void reconnect() {
  // Loop até estar conectado
  while (!client.connected()) {
    Serial.print("Conectando ao MQTT...");
    if (client.connect("ESP32Client", mqtt_user, mqtt_pass)) {
      Serial.println("conectado");
      // Se conectado, assina o tópico de comandos e envia uma mensagem de confirmação
      client.subscribe(mqtt_command_dim);
      client.subscribe(mqtt_command_temp1);
      client.subscribe(mqtt_command_humidity); // Assina o tópico de comandos
    } else {
      Serial.print("falhou, rc=");
      Serial.print(client.state());
      Serial.println(" tentando novamente em 5 segundos");
      // Aguarda 5 segundos antes de tentar novamente
      delay(5000);
    }
  }
}

void MarlusCloudUpdate(){

  if (!client.connected()) {
    unsigned long now = millis();
    if (now - lastReconnectAttempt > 5000) {
      lastReconnectAttempt = now;
      // Tentativa de reconexão
      if (tryReconnect()) {
        lastReconnectAttempt = 0;
      }
    }
  } else {
    // Se conectado, então processa as chegadas de mensagens
    client.loop();
  }

  // Se o envio de informações estiver parado, pisca o LED continuamente
  if (!enviarInformacoes) {
    digitalWrite( LED_BUILTIN, HIGH);
    delay(100); // Este valor determina a velocidade do piscar
    digitalWrite( LED_BUILTIN, LOW);
    delay(100);
  } else if (millis() - ultimoEnvio > intervaloEnvio) {
    ultimoEnvio = millis(); // Atualiza o tempo do último envio

    // Simula a leitura da temperatura com um valor aleatório
    float value = random(15, 25);

    // Cria o payload JSON
    String payload_dim = "{"
                         "\"value\": " + String(dim1_out) + ","
                         "\"mqttTopic\": \"bru/luz\","
                         "\"unit\" : \"%\""
                         "}";
                         
    String payload_temp1 = "{"
                         "\"value\": " + String(temperature) + ","
                         "\"mqttTopic\": \"bru/temp1\","
                         "\"unit\" : \"C\""
                         "}";

    String payload_humidity = "{"
                         "\"value\": " + String(humidity) + ","
                         "\"mqttTopic\": \"bru/temp1\","
                         "\"unit\" : \"%\""
                         "}";

    // Envia o payload
    client.publish(mqtt_dim, payload_dim.c_str(), true);
    client.publish(mqtt_temp1, payload_temp1.c_str(), true);
    client.publish(mqtt_humidity, payload_humidity.c_str(), true);
  }
  
}

void loop(){
  
  if( millis() > ( millisPrev + loopPeriod ) ){
    
    millisPrev = millis();

    MarlusCloudUpdate();
    
    refreshNow();
    
    dht22Read();
    
    setDimming();
    
    //showTime();
    
    onDacAutoChange();
    
    //checkDeviceStatus();
    
    //checkMidnightReset();
    
    //clockSync();
    
    watchDogFeed();

    if( Serial.available() ) handleSerialInput();
    
  }

}

void bootLog(){
  
  File boot_log_fp = SD.open( "/blg.txt" , FILE_APPEND );
  
  refreshNow();
  
  if( boot_log_fp ){
    
    Serial.println("Registrando boot no arquivo de log...");
    
    boot_log_fp.print(now.day(), DEC);
    boot_log_fp.print('/');
    boot_log_fp.print(now.month(), DEC);
    boot_log_fp.print('/');
    boot_log_fp.print(now.year(), DEC);
    boot_log_fp.print(" (");
    boot_log_fp.print(daysOfTheWeek[now.dayOfTheWeek()]);
    boot_log_fp.print(") ");
    boot_log_fp.print(now.hour(), DEC);
    boot_log_fp.print(':');
    boot_log_fp.print(now.minute(), DEC);
    boot_log_fp.print(':');
    boot_log_fp.print(now.second(), DEC);
    boot_log_fp.println();
    
    // close the file:
    boot_log_fp.close();
    Serial.println("Boot resgistrado com sucesso.");
    
  }else{
    
    // if the file didn't open, print an error:
    Serial.println("Erro ao abrir o arquivo blg.txt");
    
  }
  
}

void refreshNow(){
  
  now = rtc.now();
  
}
/*
void clockSync(){
  
  if( ArduinoCloud.connected() == 1 && ArduinoCloud.getLocalTime() > 0 && clockInSync == 0 ){
      
    Serial.println(F("Sicronizando RTC interno com a Arduino Cloud..."));
     
    rtc.adjust( DateTime( ArduinoCloud.getLocalTime() ) ); 
    
    Serial.println(F("RTC sicronizado com sucesso!"));
    
    clockInSync = 1;
    
  }
  
}
*/
void watchDogFeed(){
  
  digitalWrite( WTD_PIN , !digitalRead( WTD_PIN ) );
  
  //Serial.println("\nFlip Watchdog\n");
  
}

void checkMidnightReset(){
  
  //if( now.hour() < prevHour ){
  if( now.hour() == 12 && prevHour == 11 ){
      
    Serial.println(F("Reiniciando ESP32..."));
    
    ESP.restart();
      
  }
  
  prevHour = now.hour();
  
}
/*
void checkDeviceStatus(){
  
  if( ArduinoCloud.connected() == 0 ){
  
    cloudDisconnectedCounter++;
    
    Serial.print("Cloud desconetada! Tentando reconectar ["); 
    Serial.print(cloudDisconnectedCounter);
    Serial.print("/");
    Serial.print(CLOUD_DISCONNECTED_COUNTER_MAX);
    Serial.println("]...");
    
  }else{
    
    if( cloudDisconnectedCounter > 0 ) Serial.println("Cloud conetada!");
    
    cloudDisconnectedCounter = 0;
    
  }
  
  if( cloudDisconnectedCounter >= CLOUD_DISCONNECTED_COUNTER_MAX ){
    
    Serial.print("Reiniciando ESP32...");
    
    ESP.restart();
    
  }
  
}
*/
void handleSerialInput(){
  
  String MonitorInput;
  
  MonitorInput = Serial.readString();
  MonitorInput.trim();
    
  if ( MonitorInput.substring(0) == "rtc" ) setRTCtime();
  
}

void setRTCtime(){
  
  uint16_t year;
  uint8_t month, day, hour, minute, second;
  
  Serial.print("Novo valor para ano (AAAA): ");
  while( !Serial.available() );
  year = Serial.parseInt();
  Serial.println();
  if( Serial.available() )Serial.read();
  
  Serial.print("Novo valor para mês (MM): ");
  while( !Serial.available() );
  month = Serial.parseInt();
  Serial.println();
  if( Serial.available() )Serial.read();
  
  Serial.print("Novo valor para dia (DD): ");
  while( !Serial.available() );
  day = Serial.parseInt();
  Serial.println();
  if( Serial.available() )Serial.read();
  
  Serial.print("Novo valor para horas (hh): ");
  while( !Serial.available() );
  hour = Serial.parseInt();
  Serial.println();
  if( Serial.available() )Serial.read();
  
  Serial.print("Novo valor para minutos (mm): ");
  while( !Serial.available() );
  minute = Serial.parseInt();
  Serial.println();
  if( Serial.available() )Serial.read();
  
  Serial.print("Novo valor para segundos (ss): ");
  while( !Serial.available() );
  second = Serial.parseInt();
  Serial.println();
  if( Serial.available() )Serial.read();
  
  rtc.adjust( DateTime( year , month , day , hour , minute , second ) );
  
  Serial.println("Relogio ajustado com sucesso! ");
  
}

void dht22Read(){
  
  temperature = dht.readTemperature() * DHT_TEMPERATURE_GAIN + DHT_TEMPERATURE_OFFSET;
  humidity = dht.readHumidity() * DHT_HUMIDITY_GAIN + DHT_HUMIDITY_OFFSET;
  
  //Serial.print(F("Temperature - ")); Serial.print(t); Serial.println(F(" C"));
  //Serial.print(F("Humidity - ")); Serial.print(h); Serial.println(F(" %"));
  
}

long HMStoSeconds( uint8_t _hours , uint8_t _minutes , uint8_t _seconds ){
  
  return( _hours * 3600 + _minutes * 60 + _seconds );
  
}

void setDimming(){
  
  if( dac_Auto == 1 ){
    
    int8_t dim1, dim2, dim3, dim4, dim5, dim6, dim7, dim8;
    
    dim1 = mapDimmingTable( &dimCH1 );
    dim2 = mapDimmingTable( &dimCH2 ); 
    dim3 = mapDimmingTable( &dimCH3 ); 
    dim4 = mapDimmingTable( &dimCH4 ); 
    //dim5 = mapDimmingTable( &dimCH5 ); 
    //dim6 = mapDimmingTable( &dimCH6 ); 
    //dim7 = mapDimmingTable( &dimCH7 ); 
    //dim8 = mapDimmingTable( &dimCH8 ); 

    if( dim1 == -1 && dim2 == -1 && dim3 == -1 && dim4 == -1 && dim5 == -1 && dim6 == -1 && dim7 == -1 && dim8 == -1 ){
      relay_pin_1_out = LOW;
    }
    else{
      relay_pin_1_out = HIGH;
    } 
    digitalWrite( RELAY_PIN_1 , relay_pin_1_out );
    
    if( dim1 < 0 ) dim1 = 0;
    if( dim2 < 0 ) dim2 = 0;
    if( dim3 < 0 ) dim3 = 0;
    if( dim4 < 0 ) dim4 = 0;
    //if( dim5 < 0 ) dim5 = 0;
    //if( dim6 < 0 ) dim6 = 0;
    //if( dim7 < 0 ) dim7 = 0;
    //if( dim8 < 0 ) dim8 = 0;
    
    Serial.print(dim1);Serial.print(" ");
    Serial.print(dim2);Serial.print(" ");
    Serial.print(dim3);Serial.print(" ");
    Serial.print(dim4);Serial.print(" ");
    //Serial.print(dim5);Serial.print(" ");
    //Serial.print(dim6);Serial.print(" ");
    //Serial.print(dim7);Serial.print(" ");
    //Serial.print(dim8);Serial.println();
    
    dim1_out = dim1;
    dim2_out = dim2;
    dim3_out = dim3;
    dim4_out = dim4;
    //dim5_out = dim5;
    //dim6_out = dim6;
    //dim7_out = dim7;
    //dim8_out = dim8;
    
    dim1 = map_i8( dim1 , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
    dim2 = map_i8( dim2 , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
    dim3 = map_i8( dim3 , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
    dim4 = map_i8( dim4 , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
    //dim5 = map_i8( dim5 , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
    //dim6 = map_i8( dim6 , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
    //dim7 = map_i8( dim7 , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
    //dim8 = map_i8( dim8 , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
    
    Serial.print(dim1);Serial.print(" ");
    Serial.print(dim2);Serial.print(" ");
    Serial.print(dim3);Serial.print(" ");
    Serial.print(dim4);Serial.print(" ");
    //Serial.print(dim5);Serial.print(" ");
    //Serial.print(dim6);Serial.print(" ");
    //Serial.print(dim7);Serial.print(" ");
    //Serial.print(dim8);Serial.println();
    
    dac1_out.setVoltage( (uint16_t)( (uint16_t)dim1 * 4095 / 100 ) , false );
    dac2_out.setVoltage( (uint16_t)( (uint16_t)dim2 * 4095 / 100 ) , false );
    dac3_out.setVoltage( (uint16_t)( (uint16_t)dim3 * 4095 / 100 ) , false );
    dac4_out.setVoltage( (uint16_t)( (uint16_t)dim4 * 4095 / 100 ) , false );
    //pwm.write( PWM_PIN_1 , (int32_t)( (int32_t)dim5 * 4095 / 100 ) , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
    //pwm.write( PWM_PIN_2 , (int32_t)( (int32_t)dim6 * 4095 / 100 ) , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
    //pwm.write( PWM_PIN_3 , (int32_t)( (int32_t)dim7 * 4095 / 100 ) , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
    //pwm.write( PWM_PIN_4 , (int32_t)( (int32_t)dim8 * 4095 / 100 ) , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
    
  }else{
    
    if( dac1_in < 0.01 && dac2_in < 0.01 && dac3_in < 0.01 && dac4_in < 0.01 && dac5_in < 0.01 && dac6_in < 0.01 && dac7_in < 0.01 && dac8_in < 0.01 ){
      relay_pin_1_out = LOW;
    }
    else{
      relay_pin_1_out = HIGH;
    }
    digitalWrite( RELAY_PIN_1 , relay_pin_1_out );
    
  }
  
}

uint8_t mapDimmingTable( dimming_t *dimming ){
  
  uint8_t dimming_value;
  long _seconds;
  
  _seconds = HMStoSeconds( now.hour() , now.minute() , now.second() );
  _seconds = ( _seconds - HMStoSeconds( dimming->hours[0] , dimming->minutes[0] , dimming->seconds[0] ) );
  
  if( _seconds < 0 ) return( -1 );
  
  if( _seconds > ( HMStoSeconds( dimming->hours[dimming->dimmingPoints-1] , dimming->minutes[dimming->dimmingPoints-1] , dimming->seconds[dimming->dimmingPoints-1] ) - HMStoSeconds( dimming->hours[0] , dimming->minutes[0] , dimming->seconds[0] ) ) ) return( -1 );
  
  for( uint8_t counter = 0 ; counter < dimming->dimmingPoints ; counter++ ){
   
    if( dimming->secondsSinceStart[counter] > _seconds ){
      
      dimming_value = map( _seconds , 
                           dimming->secondsSinceStart[counter-1] ,
                           dimming->secondsSinceStart[counter] ,
                           dimming->value[counter-1] ,
                           dimming->value[counter] );
      
      break;
      
    }
    
  }
  
  return( dimming_value );
  
}

void readFile( fs::FS &fs , const char * path , dimming_t *dimming ){

  File file = fs.open( path );
  if( !file ){
      Serial.println("Failed to open file for reading");
      return;
  }

  for( uint8_t counter = 0 ; counter < DIMMING_POINTS_MAX ; counter ++ ){
    
    dimming->hours[counter] = file.parseInt(); 
    dimming->minutes[counter] = file.parseInt();
    dimming->seconds[counter] = file.parseInt();
    
    if( !file.available() )break;
    
    dimming->value[counter] = file.parseInt();
    
    dimming->dimmingPoints = ( counter + 1 );
    
  }
  
  //Serial.println(dimming->dimmingPoints);
  
  file.close();
    
}

void getSecondsSinceStart( dimming_t *dimming ){
  
  for( uint8_t counter = 0 ; counter < dimming->dimmingPoints ; counter++ ){
    
    dimming->secondsSinceStart[counter] = HMStoSeconds( dimming->hours[counter] ,
                                                        dimming->minutes[counter] ,
                                                        dimming->seconds[counter] );
                                               
    dimming->secondsSinceStart[counter] = dimming->secondsSinceStart[counter] -
                                          HMStoSeconds( dimming->hours[0] ,
                                                        dimming->minutes[0] ,
                                                        dimming->seconds[0] );
                                                       
  }
  
}

void getDimmingTable(){
  
  readFile( SD , "/ch1.txt" , &dimCH1 ); getSecondsSinceStart( &dimCH1 );
  readFile( SD , "/ch2.txt" , &dimCH2 ); getSecondsSinceStart( &dimCH2 );
  readFile( SD , "/ch3.txt" , &dimCH3 ); getSecondsSinceStart( &dimCH3 );
  readFile( SD , "/ch4.txt" , &dimCH4 ); getSecondsSinceStart( &dimCH4 );
  //readFile( SD , "/ch5.txt" , &dimCH5 ); getSecondsSinceStart( &dimCH5 );
  //readFile( SD , "/ch6.txt" , &dimCH6 ); getSecondsSinceStart( &dimCH6 );
  //readFile( SD , "/ch7.txt" , &dimCH7 ); getSecondsSinceStart( &dimCH7 );
  //readFile( SD , "/ch8.txt" , &dimCH8 ); getSecondsSinceStart( &dimCH8 );
  
}

void onDac1InChange(){
  // Add your code here to act upon Dac1In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac1_in , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
  //Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim1_out = dac1_in;
    dac1_out.setVoltage( dim , false );
  }
  
}

void onDac2InChange(){
  // Add your code here to act upon Dac2In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac2_in , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
  //Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim2_out = dac2_in;
    dac2_out.setVoltage( dim , false );
  }
  
}

void onDac3InChange(){
  // Add your code here to act upon Dac3In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac3_in , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
  //Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim3_out = dac3_in;
    dac3_out.setVoltage( dim , false );
  }
  
}

void onDac4InChange(){
  // Add your code here to act upon Dac4In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac4_in , 0 , 100 , DIMMING_MIN_DAC , DIMMING_MAX_DAC );
  //Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim4_out = dac4_in;
    dac4_out.setVoltage( dim , false );
  }
  
}
/*
void onDac5InChange(){
  // Add your code here to act upon Dac5In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac5_in , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
  Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim5_out = dac5_in;
    pwm.write( PWM_PIN_1 , (int32_t)dim , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase  );
  }
  
}

void onDac6InChange(){
  // Add your code here to act upon Dac6In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac6_in , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
  Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim6_out = dac6_in;
    pwm.write( PWM_PIN_2 , (int32_t)dim , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
  }
  
}

void onDac7InChange(){
  // Add your code here to act upon Dac7In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac7_in , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
  Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim7_out = dac7_in;
    pwm.write( PWM_PIN_3 , (int32_t)dim , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
  }
  
}

void onDac8InChange(){
  // Add your code here to act upon Dac8In change
  
  int16_t dim;
  dim = map_i16( (uint16_t)dac8_in , 0 , 100 , DIMMING_MIN_PWM , DIMMING_MAX_PWM );
  Serial.println( dim );
  dim = dim * 4095 / 100;
  
  if( !dac_Auto ){
    dim8_out = dac8_in;
    pwm.write( PWM_PIN_4 , (int32_t)dim , DefaultPWMfrequency , DefaultPWMresolution , DefaultPWMphase );
  }
  
}
*/
void showTime(){
  
  Serial.print(now.year(), DEC);
  Serial.print('/');
  Serial.print(now.month(), DEC);
  Serial.print('/');
  Serial.print(now.day(), DEC);
  Serial.print(" (");
  Serial.print(daysOfTheWeek[now.dayOfTheWeek()]);
  Serial.print(") ");
  Serial.print(now.hour(), DEC);
  Serial.print(':');
  Serial.print(now.minute(), DEC);
  Serial.print(':');
  Serial.print(now.second(), DEC);
  Serial.println();
  
}

void onDacAutoChange(){
  // Add your code here to act upon DacAuto change
  
  if( dac_Auto == 1 ) digitalWrite( LED_BUILTIN , HIGH );
  else digitalWrite( LED_BUILTIN , LOW );
  
  onDac1InChange();
  onDac2InChange();
  onDac3InChange();
  onDac4InChange();
  //onDac5InChange();
  //onDac6InChange();
  //onDac7InChange();
  //onDac8InChange();
  
}

int8_t map_i8(int8_t x, int8_t in_min, int8_t in_max, int8_t out_min, int8_t out_max){
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}

int16_t map_i16(int16_t x, int16_t in_min, int16_t in_max, int16_t out_min, int16_t out_max){
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}

int32_t map_i32(int32_t x, int32_t in_min, int32_t in_max, int32_t out_min, int32_t out_max){
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
